### PR TITLE
fix #40 and #41

### LINKED ISSUE #40: weird acceptable range of loop times
## How to reproduce
1. Open wnr.
2. Set the values to loop for 1.7 times.
3. The timing functionality still works with some weird interesting behaviors (e. g. looping count keeps increasing at every second forever and ever). Neither error nor warning was given.

In the case of looping for 0 times, wnr will never stop looping, like the infinity mode. Is it a feature?

### LINKED ISSUE #41: weird "all together" information when specific time intervals (<= 1 or float point) are given
## How to reproduce (time interval <= 1)
1. Open wnr.
2. Set the values to "work for 1 minute, rest for 1 minute and loop for once".
3. The "all together" information does not come out but the timing functionality still works fine.

## How to reproduce (time interval is a float point value)
1. Open wnr.
1. Set the values to "work for 1.8 minute, rest for 1.1 minute and loop for once".
2. The "all together" information shows that there are all together 2 minutes. However, the exact value of the sum is 2.9 minutes which is closer to 3 minutes.

### PR DESCRIPTION
**Pull request by NKID00**
Fix #41.

### CODE REVIEW

**Comment by NKID00** [comment]
Fix #40.

**Comment by RoderickQiu** [comment]
thank you dude!
let my check this one out now.

**Comment by RoderickQiu** [comment]
just perfect and 've merged! thanks you!

**Comment by RoderickQiu** [comment]
i think i shall have next version the next week 'cause there has been more than a month without a release..
i'll also adapt it to electron 12 in the next release, i suppose.

**Comment by RoderickQiu** [comment]
the new version is released!
https://scris.lanzoui.com/b01n0tb4j

**Pull request merged**
